- name: k8sapi
  selector:
    matchLabels:
      workflows.argoproj.io/container-runtime-executor: k8sapi
- name: emissary
  selector:
    matchLabels:
      workflows.argoproj.io/container-runtime-executor: emissary